[package]
name = "bb-dash"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
reqwest = { version = "0.12", features = ["json"]}
serde = "1"
tokio = { version = "1", features = ["full"]}
anyhow = "1.0"
